name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - ipywidgets
  - pandas
  - voila
  - numpy
  - matplotlib
  - scipy
  - jupyterlab
  - notebook
  - nbconvert
  - nbformat
  - openpyxl
  - pip:
      - pymupdf==1.23.25
